# Generated by Django 5.1.7 on 2025-03-13 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitales', '0002_dept_emp_departamento_alter_hospital_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hospital',
            table='HOSPITAL',
        ),
    ]
